### ISSUE TITLE
[Ory Hydra] broken link for hydra install guide

### ISSUE THREAD

**Issue by HungUnicorn** [ory/docs#525]
https://www.ory.sh/hydra/docs/guides/gitlab/#preparation

points to

https://www.ory.sh/hydra/docs/guides/install

which is broken

**Comment by aeneasr** [comment]
@vinckr could you take a look? :)

**Comment by vinckr** [comment]
This is a bug when you link to an anchor.

When I go to 
https://www.ory.sh/hydra/docs/guides/gitlab/#preparation
or 
https://www.ory.sh/hydra/docs/guides/gitlab/#spin-up-the-instances-and-logging-in

When not linking to an anchor it does not happen. 

So for example, if we have this URL
`https://www.ory.sh/hydra/docs/guides/gitlab/#spin-up-the-instances-and-logging-in`
it goes one level "up", so ends up at 
`https://www.ory.sh/hydra/docs/guides/`, when it should be `https://www.ory.sh/hydra/docs/`, as it parses the /gitlab/ part as folder basically. 

A quick search in docusaurus repo did not really produce anything. As this only arises when linking to anchors, if we dont do it, we should be fine. 

Linking to anchors is bad practice anway since they change when the headline changes and then we need to add redirects and so on...

**Comment by vinckr** [comment]
Nice! That would make linking to anchors safe. 
But it would still not solve this issue right?
